### ISSUE TITLE
How to generate preprocess dataset?

### ISSUE THREAD

**Issue by rockywind** [astra-vision/SceneRF#1]
Hi, @anhquancao 
I don't know how to generate the preprocess dataset.
Is it the same as the monoscene data preprocess [script](https://github.com/astra-vision/MonoScene/blob/master/monoscene/data/semantic_kitti/preprocess.py)

**Comment by anhquancao** [comment]
Hi @rockywind,
The preprocess data will be generated during training. 
https://github.com/astra-vision/SceneRF/blob/main/scenerf/data/semantic_kitti/kitti_dataset.py#L329
It is the refined transformation matrix output from ICP.

**Comment by rockywind** [comment]
Thanks!
