### ISSUE TITLE
About to generate mesh

### ISSUE THREAD

**Issue by wangqiwangyuqing** [astra-vision/SceneRF#12]
Hi, I want to know when  this section of code will be added.

**Comment by anhquancao** [comment]
Hi, you can obtain the mesh from this code
https://github.com/astra-vision/SceneRF/blob/main/scenerf/scripts/reconstruction/depth2tsdf.py#L107

**Comment by anhquancao** [comment]
Hi @wangqiwangyuqing,
I added a section on mesh visualization:
https://github.com/astra-vision/SceneRF/blob/main/README.md#mesh-extraction-and-visualization
