### ISSUE TITLE
Questions about code

### ISSUE THREAD

**Issue by Korace0v0** [astra-vision/SceneRF#13]
Hi, thanks for your kind help last time. Now I'm learning NeRF from your code. It's a really great work but I am not good at coding. I met some problems in learning. I will try to list them below.

1. I find some conv layers seem not to be used in the network. They are self.resize_1_1 to self.resize_output_1_16 in scenerf/models/unet2d_sphere.py. Should I delete these layers?

2. I find 'steps' appear repeatedly in scenerf/models/utils/sample_rel_poses. Should I use the first line?
    steps = torch.arange(start=0, end=max_distance, step=step)
    steps = torch.arange(start=0, end=0.6, step=0.5)

3. In scenerf/models/utils/uniform_sampling, the step of noise seems not to be consistent with sensor_distance_sampled, as the intervals of torch.linspace will be n_pts_per_ray-1 instead of n_pts_per_ray. Is this ok?

Thank you very much again!

**Comment by anhquancao** [comment]
Hello @zhangfang97,

Thank you for expressing your interest! Here are my responses to your queries:

1. Yes, you should delete those lines. I cleaned up the code for publishing, but I may have missed those lines.

2. The first line is accurate.

3. I have specified the steps in torch.linspace such that it will sample n_pts_per_ray.
```
sensor_distance_sampled = torch.linspace(d_min, d_max,
                                             steps=n_pts_per_ray,
                                             device=unit_direction.device)
```

**Comment by Korace0v0** [comment]
Thanks for your quick reply! I understand the first two responses. For the third one, I'm sorry I didn't make it clear. I will try to explain what I am concerned about. 

As sensor_distance_sampled is added by noise, I was wondering if the noise[i] is used to move the sensor_distance_sampled[i] to the interval of (sensor_distance_sampled[i],  sensor_distance_sampled[i+1]).

Through using torch.linspace, sensor_distance_sampled will have n_pts_per_ray, but the distance of two consecutive points will be (d_max-d_min)/(n_pts_per_ray-1). 
At the same time, the interval of noise is (d_max-d_min)/n_pts_per_ray, which may exceed the boundary of (sensor_distance_sampled[i],  sensor_distance_sampled[i+1]).

Did I make a mistake or will this be ok?

**Comment by anhquancao** [comment]
Hi @zhangfang97,
You're correct that the value can exceed. I actually noticed this issue myself earlier, but I added [a step in the rendering process ](https://github.com/astra-vision/SceneRF/blob/main/scenerf/models/scenerf.py#L650)where all the points are sorted. Thus, the issue doesn't have any impact on the output.

**Comment by Korace0v0** [comment]
Thank you so much! I understand it.  

I'm truly grateful for your help. Wish you every success!  😊

**Comment by anhquancao** [comment]
No problem at all! Happy to help and glad you understood. Best of luck to you!
