### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by Korace0v0** [astra-vision/SceneRF#14]
Hi, I'm back again 😂. I seem to find a bug in this repo, but I'm not really sure.

It is in the predict function of scenerf/models/scenerf.py, 
```jsx
        feats_2d_sphere = [sample_feats_2d(x_rgb["1_1"].unsqueeze(0), pix_sphere_coords, (self.out_img_W, self.out_img_H))]
        for scale in [2, 4, 8, 16]:
            key = "1_{}".format(scale)
            feats_2d_sphere.append(sample_feats_2d(x_rgb[key].unsqueeze(0), pix_sphere_coords, (self.out_img_W//scale, self.out_img_H//scale)))
        
```

The input pix_sphere_coords of sample_feats_2d is used for different downsample resolution, but (img_w, img_H) has beed changed.
In sample_feats_2d,  pix_sphere_coords is divided by (img_W, img_H), which will cause the bound of projected_pix becomes much smaller than (-1,1) according to the downsample ratio. This will lead to a lot of zeros in feats_2d.
```jsx
    projected_pix = (projected_pix / torch.tensor(img_size).type_as(projected_pix).reshape(1, 2)) * 2 - 1
    projected_pix = projected_pix.reshape(1, 1, -1, 2)
```

Did I make a mistake? Many thanks!

**Comment by anhquancao** [comment]
Hey @zhangfang97, thank you for bringing this to my attention! I double-checked with my offline code, and you were right - the correct code should be:
```
feats_2d_sphere.append(sample_feats_2d(x_rgb[key].unsqueeze(0), pix_sphere_coords, (self.out_img_W, self.out_img_H)))
```
It's not necessary to divide by the scale.

**Comment by Korace0v0** [comment]
I got it. I'm glad this can work and thank you again!

**Comment by anhquancao** [comment]
You're welcome! Glad I could help.
