### ISSUE TITLE
Something wrong when I want to compute the depth metrics on all frames in each sequence

### ISSUE THREAD

**Issue by wangqiwangyuqing** [astra-vision/SceneRF#15]
Hi, today when I want to compute the depth metrics on all frames in each sequence follow your instructions, I met an error.
<img width="774" alt="b38c56d79e311aa1cad611a26fb404a" src="https://user-images.githubusercontent.com/92991640/235480212-08728a66-038a-4ae9-aed0-231fcb4cc3a6.png">
May I ask that did you met this problem before? 
I print the variable, it looks like 
<img width="773" alt="fd2271f2e63dac2d352d42679e9ab7b" src="https://user-images.githubusercontent.com/92991640/235480607-4d6ee185-6585-4efd-87cb-571e43116af2.png">
I tried some methods like using "torch.unsqueeze()" to expand dimensions but it doesn't work. I have no idea on how to fix it now.  :(
Sorry to bother you.

**Comment by anhquancao** [comment]
Hi @wangqiwangyuqing, thank you for pointing out the error, let me check it and will get back to you this week.

**Comment by anhquancao** [comment]
It's weird that you have ~4k frames. For validation, there are only 800 frames since we only use the frame_id % 5 == 0 as in this line of code.
https://github.com/astra-vision/SceneRF/blob/main/scenerf/data/semantic_kitti/kitti_dataset.py#L95 

Can you check if the variable self.scans in the following line contains only frames with frame_id % 5 == 0 
https://github.com/astra-vision/SceneRF/blob/main/scenerf/data/semantic_kitti/kitti_dataset.py#L165

**Comment by BeileiCui** [comment]
@anhquancao Hi. I met the same error and my validation only contains frame_id % 5 == 0
![1684472670199](https://github.com/astra-vision/SceneRF/assets/114715678/c93c63d5-6b7d-4132-8d13-1fd0a4ea4b10)
looking forward to your reply!

**Comment by anhquancao** [comment]
Hi @BeileiCui, thanks for your info.
It's really weird, I cloned the code, downloaded the checkpoint and ran the evaluation. However, my evaluation passed item 92/799 and had no error.
![Screenshot from 2023-05-19 11-24-31](https://github.com/astra-vision/SceneRF/assets/9668858/544f96b2-6baf-48e5-b178-bdbb94b266c6)

Did you following my instruction to setup the dataset?
https://github.com/astra-vision/SceneRF#dataset

Which command did you use?

Can you print the length of weights_at_depth and the shape of the tensor inside?

**Comment by anhquancao** [comment]
Can you change the line 737 as following in scenerf.py and try again @wangqiwangyuqing  @BeileiCui ?
https://github.com/astra-vision/SceneRF/blob/main/scenerf/models/scenerf.py#L737

The error is when there is only 1 ray, the squeeze() function turns the array of 1 item into a scalar which causes the issue in torch.cat. So the solution is to change "squeeze()" to "squeeze(-1)".

**Comment by wangqiwangyuqing** [comment]
> Can you change the line 737 as following in scenerf.py and try again @wangqiwangyuqing @BeileiCui ? https://github.com/astra-vision/SceneRF/blob/main/scenerf/models/scenerf.py#L737
> 
> The error is when there is only 1 ray, the squeeze() function turns the array of 1 item into a scalar which causes the issue in torch.cat. So the solution is to change "squeeze()" to "squeeze(-1)".

Hi, I changed "squeeze()" to "squeeze(-1)", but still have the same problem.

**Comment by BeileiCui** [comment]
Hi @anhquancao I tried your suggestion to change "squeeze()" to "squeeze(-1)" and the problem is solved! Really thanks for your time!

**Comment by anhquancao** [comment]
Great! You are welcome.
