### ISSUE TITLE
Bugs in generate_novel_depths.py

### ISSUE THREAD

**Issue by II-Matto** [astra-vision/SceneRF#17]
There is a bug in `scenerf/scripts/reconstruction/generate_novel_depths.py`. The `step` variable on [L70](https://github.com/astra-vision/SceneRF/blob/main/scenerf/scripts/reconstruction/generate_novel_depths.py#L70) for computing poses is overwritten in the inner `for` loop on [L82](https://github.com/astra-vision/SceneRF/blob/main/scenerf/scripts/reconstruction/generate_novel_depths.py#L82). This results in computing depth with only 0m and 10m, ignoring 0.5m, 1.0m, 1.5m, etc.

**Comment by anhquancao** [comment]
Hi @II-Matto, Thank you for pointing out the bug. the sample_rel_poses should be outside the for loop. 
I changed [as following](https://github.com/astra-vision/SceneRF/blob/main/scenerf/scripts/reconstruction/generate_novel_depths.py#L52).

**Comment by II-Matto** [comment]
Thanks for your prompt reply and fix.

**Comment by anhquancao** [comment]
You are welcome!
