### ISSUE TITLE
How do I set the data if I want to move the image I acquired with this code? 

### ISSUE THREAD

**Issue by YuminosukeSato** [astra-vision/SceneRF#19]
How do I set the data if I want to move the image I acquired with this code?
I have acquired a series of monocular images. I would like to compose a scene flow using these images.What additional monocular images and what do you need?

**Comment by anhquancao** [comment]
Hi @YuminosukeSato , I am not familiar with scene flow problem. Could you be more specific? 
Do you mean the generated monocular images or the monocular images in the dataset? 
What do you mean by "additional monocular images "?

**Comment by YuminosukeSato** [comment]
I will explain in detail.
I would like to reconstruct his 3D scene in SceneRF using my own dataset (a research dataset that I have taken using my own monocular camera).
So I have a question.
1. In which directory should I put the data?
2. How do I change the environment variables?
3. How should I learn different from kitti data?
4.Is there anything else I need besides the monocular camera image?

**Comment by anhquancao** [comment]
The loading of the data is [located here](https://github.com/astra-vision/SceneRF/blob/main/scenerf/data/semantic_kitti/kitti_dataset.py#L64).

You will need to adapt the camera parameters (cam_K) and camera poses of each image in the sequence.

**Comment by YuminosukeSato** [comment]
- In which directory should I put the image set (not Kitti) that I acquired myself?
- What commands should I run to train with that data?
- What commands should I run to restore 3d with this data?

**Comment by anhquancao** [comment]
Sorry, I have no idea. Probably you should adapt your dataset following KITTI data structure, then follow instruction in README.md

**Comment by yanghaoRonin** [comment]
> * In which directory should I put the image set (not Kitti) that I acquired myself?
> * What commands should I run to train with that data?
> * What commands should I run to restore 3d with this data?

Hello, have you solved the configuration of the new data set file?
