### ISSUE TITLE
Are there any changes to the code and configuration for indoor scene reconstruction?

### ISSUE THREAD

**Issue by HouXin-J** [astra-vision/SceneRF#20]
hello! you address single-view reconstruction of complex **(and possibly large)** scenes, in a fully selfsupervised manner.
Does large mean the maximum distance of 3D reconstruction? Are there any changes to the code and configuration for indoor scene reconstruction?

**Comment by anhquancao** [comment]
Hello! By large scene, we mean real-world scene with lots of complex objects and occlusion like in outdoor driving. 
We will release the code for indoor scene before the end of next week (after the ICCV cam-ready deadline).

**Comment by HouXin-J** [comment]
Very great work! Looking forward to your work on indoor scenes.

**Comment by HouXin-J** [comment]
![image](https://github.com/astra-vision/SceneRF/assets/56544455/9140543e-3823-4862-b1d4-78631676d231)
      In Fig. 6, you show that when training on SemanticKITTI, SceneRF exhibits some generalization capability to the unseen nuScenes images. 
      Do you convert nuscene to kitti for prediction? nuscene img size 1600x900 -> 1220x370?

**Comment by anhquancao** [comment]
Hello,
I use the original nuscene image size. Here is the dataloader for nuscenes

```
class NuscenesDataset(Dataset):
    def __init__(self, root="/gpfsscratch/rech/kvd/uyl37fq/data/nuscenes"):
        self.nusc = NuScenes(version='v1.0-mini', dataroot=root, verbose=True)
        self.img_H = 900
        self.img_W = 1600
        self.voxel_size = 0.2
        self.normalize_rgb = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ])

    def __len__(self):
        return len(self.nusc.sample)

    def __getitem__(self, index):
        data = {}
        sample = self.nusc.sample[index]
        sample_record = self.nusc.get('sample', sample['token'])
        camera_token = sample_record['data']['CAM_FRONT']
        cam_record = self.nusc.get('sample_data', camera_token)


        img = Image.open(os.path.join(self.nusc.dataroot, cam_record['filename']))
        data['img_path'] = cam_record['filename']
        img = np.array(img, dtype=np.float32, copy=False) / 255.
        data['original_img'] = img
        img = self.normalize_rgb(img)
        data['img'] = img

        calib_record = self.nusc.get('calibrated_sensor', cam_record['calibrated_sensor_token'])
        cam_k = np.array(calib_record['camera_intrinsic'])
        T_velo_2_cam = np.identity(4) # reconstruct in camera coordinates 

        data['T_velo_2_cam'] = T_velo_2_cam
        data['cam_k'] = cam_k
        data['frame_id'] =  sample['token']

        return data


```

**Comment by HouXin-J** [comment]
I got it.  Thank you very much!

**Comment by anhquancao** [comment]
Hi @HouXin-J , I added the code for Bundlefusion
