### ISSUE TITLE
Are this method scene-specific?

### ISSUE THREAD

**Issue by kianyale** [astra-vision/SceneRF#21]
Hi, thanks for your great work!
I wonder if SceneRF is a scene-specific method or it can be generalized to the unseen scene.

**Comment by anhquancao** [comment]
Hello, thanks for your interest! 
SceneRF is generalizable, not scene-specific. The evaluation was done on unseen scenes.

**Comment by Fanqyu** [comment]
I get it. Thanks for your reply.

**Comment by kianyale** [comment]
I get it. Thanks for your reply.
