### ISSUE TITLE
train semantickitti problem

### ISSUE THREAD

**Issue by sullicsullic** [astra-vision/SceneRF#22]
Hi, wonderful and very novel job!
by running train_kitti.py, I found unexpected argument 'dataset'  when instancing model, 
so I just delete the argument 'dataset', as in the picture
<img width="270" alt="rfq" src="https://github.com/astra-vision/SceneRF/assets/43094873/87522399-e53f-4a0a-93fd-85c79b26ec90">
And then the program runs perfectly.

Is the argument 'dataset' useless?
Thank u

**Comment by anhquancao** [comment]
Hi @leavesullic ,
Thank you for identifying the error. Yes, the 'dataset' parameter is redundant. I probably removed it while cleaning the code for BundleFusion but forgot to update it for the KITTI dataset.

**Comment by sullicsullic** [comment]
thanks~~
