### ISSUE TITLE
Asking for preprocess tsdf of 13.84 IoU ckpt

### ISSUE THREAD

**Issue by haiphamcse** [astra-vision/SceneRF#25]
Hi there again, first of all thank you for replying to my earlier questions. I want to ask can you release the preprocessed tsdf with the 13.84 result IoU? Right now i'm trying to reproduce your scene reconstruction results but since my computation budget is small, I can only generating depth at angle=0  and step=5. But the results seems to be not as good as the paper. It would be very nice to have a preprocessed tsdf to validate the paper's results :D
![image](https://github.com/astra-vision/SceneRF/assets/76871780/aeff2e61-8d3b-489e-a527-3842a7a0b34b)

**Comment by anhquancao** [comment]
No problem, I will try to regenerate it next week, probably after Thursday since I have an important deadline.

**Comment by anhquancao** [comment]
Hello, I've just realized that running this task would require approximately 100 hours of GPU time, and at the moment, I need to conserve my GPU hours for CVPR. Would it be an issue if I generate the results after the CVPR deadline

**Comment by haiphamcse** [comment]
Thank you for your reply. It would not be a problem. Thank you for supporting the community! I will close the issue now, you can revisit this when you have the time.

**Comment by anhquancao** [comment]
Thanks for your understanding! Don't hesitate to ping me after CVPR deadline.

**Comment by anhquancao** [comment]
Hello @haiphamcse , I suggest taking a look at the paper "MonoNeRD: NeRF-like Representations for Monocular 3D Object Detection." In this research, the density field is calculated based on the Signed Distance Function (SDF), simplifying the process of extracting occupancy. When you optimize the density field, you simultaneously optimize the underlying SDF, and it is straightforward to obtain occupancy directly from the SDF.
