### ISSUE TITLE
No Module named scenerf" 

### ISSUE THREAD

**Issue by yanghaoRonin** [astra-vision/SceneRF#26]
Why does "No Module named scenerf" keep appearing during verification?

**Comment by anhquancao** [comment]
Hello, I didn't have this problem? Can you elaborate more like which script did you run? did you run "pip install --ve ./" as in the installation guide in the Readme?

**Comment by yanghaoRonin** [comment]
I have piped all the requirements, but when running the save_depth_metrics.py script. from scenerf.models.scenerf import scenerf This code says "No Module named scenerf"

**Comment by anhquancao** [comment]
Ah sorry, I see the problem, can you change " from scenerf.models.scenerf import scenerf" to "from scenerf.models.scenerf import SceneRF as scenerf".

**Comment by yanghaoRonin** [comment]
Here I have tried to modify, but still can not, still report the same error

**Comment by yanghaoRonin** [comment]
I have solved this problem, thank you very much

**Comment by anhquancao** [comment]
Hello, can you tell me what is the error so that I can fix it?
Thank you in advance,
Anh-Quan

**Comment by yanghaoRonin** [comment]
I reinstalled the environment you were talking about,and change " from scenerf.models.scenerf import scenerf" to "from scenerf.models.scenerf import SceneRF as scenerf".

**Comment by anhquancao** [comment]
Thank you very much for your answer!
