### ISSUE TITLE
The details of converting image coordinates to spherical coordinates are somewhat confusing

### ISSUE THREAD

**Issue by kianyale** [astra-vision/SceneRF#27]
Hi, thanks for your great work!
I'm a bit confused about coordinate conversion. There are a few questions. Could you please explain it？
First, which kind of camera frame is used in your implementation? 
<img width="337" alt="image" src="https://github.com/astra-vision/SceneRF/assets/108654290/51ac8643-ab54-4fac-b14b-dc4c4b59619f">
Second, in the projection formula described in the paper, what does ▽x and ▽y mean?
Third, does the spherical frame have the same axis as the camera frame?
I understand this process is projecting the image onto a sphere, which enlarges the FOV, but the formula is really difficult to understand if considering details.

**Comment by anhquancao** [comment]
Hi, in nutshell what I did was: for each pixel, compute the vertical and horizontal angle w.r.t. vertical axis (could be point up or down) and horizontal axis (point left or right). The actual coordinate doesn't matter as long as they are always computed w.r.t. the same axis.
