### ISSUE TITLE
[Question] 3D reconstruction from image slides

### ISSUE THREAD

**Issue by phamkhactu** [astra-vision/SceneRF#28]
Thank for great repo

I have list images from 360 degree continue. How can I make 3D reconstructions (360) image from slide?

Thank you.

**Comment by anhquancao** [comment]
Hi! can you be more specific about your setting? I don't understand what is "image from slide". Do you want to train or only infer?

**Comment by phamkhactu** [comment]
Sorry for late response! yeah it is a stitch image for creating panorama. At that time, I've solved it.
Thank you very much!
