### ISSUE TITLE
Error in Chekcpoints Saving

### ISSUE THREAD

**Issue by Gaaaavin** [astra-vision/SceneRF#29]
I tried to run the training script on SemanticKITTI dataset. However, I find the training process only saves the model at epoch 0.

I noticed that in in `scenerf/scripts/train_kitti.py`, the checkpoint is defined as 
```
ModelCheckpoint(
    save_last=True,
    monitor="valdepth/abs_rel",
    save_top_k=1,
    mode="max",
    filename="{epoch:03d}-{valdepth/abs_rel:.4f}",
)
```
I suppose the saving mode `max` is a typo and it should be `min`. Please let me know if I'm correct. Thank you.

**Comment by anhquancao** [comment]
Yes, you are correct! Actually, I always use the last checkpoint.
