### ISSUE TITLE
Question about Function "depth2disp"

### ISSUE THREAD

**Issue by xiexieren** [astra-vision/SceneRF#30]
I have a question about the function "depth2disp" which is defined in "scenerf/models/utils.py":

```
def depth2disp(depth, min_depth=0.1, max_depth=100):
    """Convert depth to disp
    """
    depth = torch.clamp(depth, min=min_depth, max=max_depth)
    min_disp = 1 / max_depth
    max_disp = 1 / min_depth
    scaled_disp = 1 / depth
    disp = scaled_disp - min_disp / (max_disp - min_disp)

    return disp
```

Is the expression "disp = scaled_disp - min_disp / (max_disp - min_disp)" missing a parenthesis？I guess it should be "disp = (scaled_disp - min_disp) / (max_disp - min_disp)"?

**Comment by anhquancao** [comment]
Hi @xiexieren ,

Indeed, you are right. I remembered I derived based on [this function ](https://github.com/nianticlabs/monodepth2/blob/master/layers.py#L16)in monodepth2.

Fortunately, I only use it for visualization.

**Comment by xiexieren** [comment]
OK, thank you!
