### ISSUE TITLE
Error with training on single gpu.

### ISSUE THREAD

**Issue by UESTCSober** [astra-vision/SceneRF#31]
When I set the parameter '--n_gpus' to 1, error occurs as follow.
  File "/home/sober/SceneRF-main/scenerf/models/unet2d_sphere.py", line 247, in forward
    encoded_feats = self.encoder(x)
  File "/home/sober/anaconda3/envs/scenerf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sober/SceneRF-main/scenerf/models/unet2d_sphere.py", line 217, in forward
    for k, v in self.original_model._modules.items():
AttributeError: 'collections.OrderedDict' object has no attribute '_modules'

**Comment by anhquancao** [comment]
Hi, currently the code is implemented to handle one item per GPU. Therefore, if you change the number of GPUs to 1, you also need to adjust the batch size to 1.

**Comment by UESTCSober** [comment]
> Hi, currently the code is implemented to handle one item per GPU. Therefore, if you change the number of GPUs to 1, you also need to adjust the batch size to 1.

Thanks for your quick reply. I set batch size = 1 as your advice and  also follow pytorch-lightning's requirment set "gpus = 1" , but the same error still occurs. In unet2d_sphere.py  class Encoder's function foward, I guess this may be a training structure with multiple GPUs, only involving multiple GPUs_ modules. Should the code be modified appropriately?

**Comment by UESTCSober** [comment]
I use "print( ) function" to check where the problem occurs.
When I maintain the code as its initial state, I can not go into line217, because Original_model is an orderedDict, it does not have attribute "_modules"
![image](https://github.com/astra-vision/SceneRF/assets/53512510/0b14e6fd-4048-466d-b5bd-34a4aab9abed)
When I change the code to delete "_modules" as this, I can not go into line218, I just got block.x.x.bnx, but k != blocks
![image](https://github.com/astra-vision/SceneRF/assets/53512510/49d1a720-6524-4ceb-ab36-ac7c80e532b0)
So will "self.original_model._modules.items( )" is necessary? 
I still set  "batch size = 1" and  "gpus = 1"

**Comment by UESTCSober** [comment]
It's my bad, bro. In unet2d_sphere.py, I set loading base model from local and use its weights model, that's why it is a orderedDict.
After set network proxy, I can start training now.
Thank you very much. The only problem is that the training speed on a single GPU is too slow. Do you think design a more lightweight model will be a optimization direction？

**Comment by anhquancao** [comment]
Hi @UESTCSober, 
I am pleased to hear that! 
Yes, the training is quite slow, I think you can checkout other NeRFs papers that  propose techniques speed up the training process like a triplane representation as in this work https://anantarb.github.io/triplanenet
