### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by LongJi12** [astra-vision/SceneRF#33]
Your work is excellent.！What is the directory structure for storing the datasets in this project?

**Comment by anhquancao** [comment]
Hi! thanks for your interest. The structures are different [depends on the datasets.](https://github.com/astra-vision/SceneRF?tab=readme-ov-file#dataset)

**Comment by LongJi12** [comment]
> Hi! thanks for your interest. The structures are different [depends on the datasets.](https://github.com/astra-vision/SceneRF?tab=readme-ov-file#dataset)

Thank you for your reply!This is the dataset structure I set up, I only used the KITTI dataset.
![image](https://github.com/astra-vision/SceneRF/assets/147734830/4a819cbf-c8c0-4b37-9cb5-9a8993cbaa48)
But when I train, it remains in this state and does not respond. What is the problem?
![image](https://github.com/astra-vision/SceneRF/assets/147734830/f78d1e90-784a-4668-b56d-ce844002625e)

**Comment by anhquancao** [comment]
You need to put the content inside data_odometry_color, data_odometry_velodyne to the `dataset` folder that contains poses. For example, you can take a look at [this code ](https://github.com/astra-vision/SceneRF/blob/main/scenerf/data/semantic_kitti/kitti_dataset.py#L65).
Similar for [images](https://github.com/astra-vision/SceneRF/blob/main/scenerf/data/semantic_kitti/kitti_dataset.py#L84) etc.

**Comment by LongJi12** [comment]
> You need to put the content inside data_odometry_color, data_odometry_velodyne to the `dataset` folder that contains poses. For example, you can take a look at [this code ](https://github.com/astra-vision/SceneRF/blob/main/scenerf/data/semantic_kitti/kitti_dataset.py#L65). Similar for [images](https://github.com/astra-vision/SceneRF/blob/main/scenerf/data/semantic_kitti/kitti_dataset.py#L84) etc.
I have moved the data set according to the tips you gave, but when I train, I still have this problem and no response. What is the problem? Is there still a problem with my data?
![image](https://github.com/astra-vision/SceneRF/assets/147734830/e4e4ae96-bbac-4e4d-95e9-876b9db922b5)

**Comment by anhquancao** [comment]
You should also check if [the variable `seq_img_paths` is not empty.](https://github.com/astra-vision/SceneRF/blob/main/scenerf/data/semantic_kitti/kitti_dataset.py#L88)

Also, your dataloader might stuck. Can you try to [set num_workers to 0](https://github.com/astra-vision/SceneRF/blob/main/scenerf/scripts/train_kitti.py#L82)?
