### ISSUE TITLE
depth estimation on other images

### ISSUE THREAD

**Issue by tazalapizza** [astra-vision/SceneRF#34]
Hello thank you for your work and your code.

Is there a simple way to perform depth estimation on custom images ?

**Comment by anhquancao** [comment]
Hi, I don't really understand your question. You can use simpler method like monodepth2 to estimate the depth.

**Comment by tazalapizza** [comment]
Sorry I meant did you release a code to use your method on a custom image, with known camera pose and parameters, to get a 3D reconstruction ? (and depth estimation consequently)

**Comment by anhquancao** [comment]
Hi, I didn't but you can just change the camera parameters in the dataloader, [for example with bundlefusion](https://github.com/astra-vision/SceneRF/blob/main/scenerf/data/bundlefusion/bundlefusion_dataset.py#L82). Then run the code to generate novel depths for bundlefusion.
