### ISSUE TITLE
Can the scene be reconstructed in 3D?

### ISSUE THREAD

**Issue by user-deng** [astra-vision/SceneRF#35]
Hello, thank you very much for your great work. Can you tell me if this model can be used to reconstruct a 3D scene, based on monocular video (video obtained without camera parameters, only with cell phone recording)?

**Comment by anhquancao** [comment]
Hi, you need to retrain it on your data which needs camera parameters and relative poses between frames. You can use SFM to obtain the poses.

**Comment by user-deng** [comment]
It seems that Scene RF is unable to directly reconstruct a 3D scene by using the already trained weights, on the input video data. So can you recommend me a few models that can reconstruct a 3D scene directly from the native data? I will be grateful.

**Comment by anhquancao** [comment]
Hi, I suggest you to try this https://github.com/naver/dust3r

**Comment by user-deng** [comment]
Thank you very much for your advice!
