### ISSUE TITLE
No module named 'scenerf'

### ISSUE THREAD

**Issue by user-deng** [astra-vision/SceneRF#36]
(scenerf) root@autodl-container-9cb9118e00-b877646d:~/autodl-tmp/SceneRF# python scenerf/scripts/train_kitti.py     --bs=1 --n_gpus=1     --enable_log=True     --preprocess_root=$KITTI_PREPROCESS     --root=$KITTI_ROOT     --logdir=$KITTI_LOG     --n_gaussians=4 --n_pts_per_gaussian=8      --max_epochs=50 --exp_prefix=Train
Traceback (most recent call last):
  File "scenerf/scripts/train_kitti.py", line 8, in <module>
    from scenerf.data.semantic_kitti.kitti_dm import KittiDataModule
ModuleNotFoundError: No module named 'scenerf'

There's nothing wrong with the reference path, why can't I find scenerf?

**Comment by anhquancao** [comment]
Hi, did you run `pip install -e ./` as in the installation instruction?
