### ISSUE TITLE
Can It can be used for Large-scale Object's Reconstruction

### ISSUE THREAD

**Issue by UESTCSober** [astra-vision/SceneRF#37]
Hello, thanks for your great work. 
I plan to use it for my graduation project, and the task I need to solve is the 3D reconstruction of freight trains, which is a very large object.
I think scene level methods should be used for 3D reconstruction of large-scale objects. Do you think SceneRF Works?
Thank you very much.

**Comment by anhquancao** [comment]
I believe the object's size isn't the main issue. The crucial factor is the variation in viewing angles of the images used for supervision. If you have a wide range of views from different angles, the model will perform well.

I also recommend checking out the paper https://arxiv.org/abs/2311.12754. It shows significant improvements compared to SceneRF.

**Comment by UESTCSober** [comment]
Thank you very much for your quick reply. I will collect my own dataset for further validation.
