### ISSUE TITLE
Question about novel depth estimation on other methods in paper 

### ISSUE THREAD

**Issue by UESTCSober** [astra-vision/SceneRF#39]
Hi, I noticed that in the experimental part of the paper, such as PixelNeRF, VisionNeRF, etc. the depth estimation is not implemented in the original paper.
But you have completed the experiments in the relevant part of your paper, I would like to ask how this is done and if possible, is it convenient to open source the code of the relevant part?
Thank you very much!

**Comment by anhquancao** [comment]
Hi @UESTCSober,

I simply replace the color with the depth of the points in the rendering equation similar to what I did in SceneRF.
