### ISSUE TITLE
generate the 3d reconstruction demo

### ISSUE THREAD

**Issue by Caroline-6** [astra-vision/SceneRF#6]
hi，i see you use the open3d plot mesh and capture the image.
i want to know  why to capture the image and how to capture the image ?

**Comment by anhquancao** [comment]
Hi, 
For each depth image, our method also renders an RGB image, which is used to colorize the mesh.

**Comment by Caroline-6** [comment]
![image](https://user-images.githubusercontent.com/42193500/211521505-e8356d19-a5fd-44aa-bca7-8de7bb26b052.png)

Thanks a lot. I have another question about the demo，Is the dynamic 3D reconstruction in the demo a video form of meshes for each input image?

**Comment by anhquancao** [comment]
Yes, the right part is the mesh reconstructed from the left input image. We infer for each frame then show them in a video

**Comment by Caroline-6** [comment]
ok，very grateful  for your help！

**Comment by anhquancao** [comment]
You are welcome!

**Comment by anhquancao** [comment]
Hi @Caroline-6 , the mesh can be generated easily following this line
https://github.com/astra-vision/SceneRF/blob/main/scenerf/scripts/reconstruction/depth2tsdf.py#L107
