### ISSUE TITLE
What's the difference between the data_odometry pose and the pose in data_odometry_labels?

### ISSUE THREAD

**Issue by rockywind** [astra-vision/SceneRF#8]
Hi, 
 I found they are two kinds of poses and different.
![image](https://user-images.githubusercontent.com/14838781/212253088-ad835483-a474-4d5d-9d00-c4ad4d222d51.png)

By the way, the pose is from world to camera. The pose is given in the camera coordinate.
Is correct?

**Comment by anhquancao** [comment]
Hi,
The poses on the left is the intrinsic parameters e.g. camera K, transform matrix from velodyne to camera cooridnates, form world to velodyne.
The poses on the right is the vehicle poses in the world coordinate from the GPS/IMU corresponding to each frame in the sequence.

**Comment by rockywind** [comment]
Thanks!
The SceneRF is use the left pose, from world coordinate to the the first frame in camera_0 coordinate?
![image](https://user-images.githubusercontent.com/14838781/212313775-9b18ecb3-9a7e-47ae-b884-fc115b7fa2c9.png).

**Comment by anhquancao** [comment]
Yes, you can take a look at this page (the blue arrow)
https://www.cvlibs.net/datasets/kitti/setup.php

**Comment by rockywind** [comment]
Thanks a lot!
