### ISSUE TITLE
Pretrained model checkoint

### ISSUE THREAD

**Issue by creatorofuniverses** [astra-vision/SceneRF#9]
Hello!

Thanks for the amazing work and discovering the source code.
I would like to try the [pre-trained model](https://drive.google.com/file/d/1mfVM2oXDw6MkWaD1Ds-PG2RBt9k-q8yE/view), but goodle drive says that the ckpt file has been moved to the trash and viewers cannot download it.

Could you please share the actual link to the pre-trained ckpt file?

![image](https://user-images.githubusercontent.com/36605305/215695700-26376d06-e54c-4f35-8601-af29c09e194f.png)

**Comment by anhquancao** [comment]
Hi! 
My bad. I accidentally deleted it. 
I recovered it. You can download using the same link.

**Comment by creatorofuniverses** [comment]
Thank you!
